from donnee import Donnee
from utilisateur import Utilisateur
from noeud import Noeud
from systeme import Systeme

if __name__ == "__main__":
    donnee0 = Donnee(0, 10)
    donnee1 = Donnee(1, 10)
    donnee2 = Donnee(2, 20)
    donnee3 = Donnee(3, 10)
    donnee4 = Donnee(4, 20)
    donnee5 = Donnee(5, 10)
    donnee6 = Donnee(6, 20)
    donnee7 = Donnee(7, 10)
    donnee8 = Donnee(8, 10)

    noeud0 = Noeud(0, 40)
    noeud1 = Noeud(1, 40)
    noeud2 = Noeud(2, 50)
    noeud3 = Noeud(3, 40)
    noeud4 = Noeud(4, 50)
    noeud0.ajouter_noeud_accessible(noeud1.get_id())
    noeud0.ajouter_noeud_accessible(noeud2.get_id())
    noeud0.ajouter_noeud_accessible(noeud3.get_id())
    noeud0.ajouter_noeud_accessible(noeud4.get_id())
    noeud1.ajouter_noeud_accessible(noeud0.get_id())
    noeud1.ajouter_noeud_accessible(noeud2.get_id())
    noeud1.ajouter_noeud_accessible(noeud3.get_id())
    noeud1.ajouter_noeud_accessible(noeud4.get_id())
    noeud2.ajouter_noeud_accessible(noeud0.get_id())
    noeud2.ajouter_noeud_accessible(noeud1.get_id())
    noeud2.ajouter_noeud_accessible(noeud3.get_id())
    noeud2.ajouter_noeud_accessible(noeud4.get_id())
    noeud3.ajouter_noeud_accessible(noeud0.get_id())
    noeud3.ajouter_noeud_accessible(noeud1.get_id())
    noeud3.ajouter_noeud_accessible(noeud2.get_id())
    noeud3.ajouter_noeud_accessible(noeud4.get_id())
    noeud4.ajouter_noeud_accessible(noeud0.get_id())
    noeud4.ajouter_noeud_accessible(noeud1.get_id())
    noeud4.ajouter_noeud_accessible(noeud2.get_id())
    noeud4.ajouter_noeud_accessible(noeud3.get_id())

    utilisateur0 = Utilisateur(0)
    utilisateur1 = Utilisateur(1)
    utilisateur2 = Utilisateur(2)
    utilisateur3 = Utilisateur(3)
    utilisateur4 = Utilisateur(4)
    utilisateur5 = Utilisateur(5)
    utilisateur6 = Utilisateur(6)
    utilisateur0.ajouter_donnee_interet(donnee0.get_id())
    utilisateur0.ajouter_noeud_accessible(noeud4.get_id())
    utilisateur1.ajouter_donnee_interet(donnee1.get_id())
    utilisateur1.ajouter_donnee_interet(donnee2.get_id())
    utilisateur1.ajouter_noeud_accessible(noeud4.get_id())
    utilisateur2.ajouter_donnee_interet(donnee5.get_id())
    utilisateur2.ajouter_donnee_interet(donnee3.get_id())
    utilisateur2.ajouter_noeud_accessible(noeud4.get_id())
    utilisateur3.ajouter_donnee_interet(donnee4.get_id())
    utilisateur3.ajouter_noeud_accessible(noeud3.get_id())
    utilisateur4.ajouter_donnee_interet(donnee6.get_id())
    utilisateur4.ajouter_noeud_accessible(noeud2.get_id())
    utilisateur5.ajouter_donnee_interet(donnee8.get_id())
    utilisateur5.ajouter_noeud_accessible(noeud1.get_id())
    utilisateur6.ajouter_donnee_interet(donnee7.get_id())
    utilisateur6.ajouter_noeud_accessible(noeud1.get_id())

    system = Systeme(1)
    system.set_liste_donnees([donnee0, donnee1, donnee2, donnee3, donnee4, donnee5, donnee6, donnee7, donnee8])
    system.set_liste_noeuds([noeud0, noeud1, noeud2, noeud3, noeud4])
    system.set_liste_utilisateurs([utilisateur0, utilisateur3, utilisateur4, utilisateur5, utilisateur6])

    system.placer_donnees()
